services:
  redis-prod:
    image: redis:7-alpine
    ports:
      - "${PROD_PORT}:6379"
    container_name: redis-prod
    command: ["redis-server", "--requirepass", "${PROD_PASS}"]
    env_file:
      - .env.prod
    networks:
      - redisnet

  nginx:
    image: nginx:alpine
    container_name: redis-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redis-prod
    networks:
      - redisnet

networks:
  redisnet:
    driver: bridge